In [1]:
 # %matplotlib inline
%pylab
import numpy as np
import cv2

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
from IPython.display import IFrame, display
file = 'Lectures/FFT2.pdf'
IFrame(file, width=550, height=400)

In [3]:
# Cargamos la imagen

image = cv2.imread('images/car.png')
cv2.imshow('ImagenOriginal',image)

In [4]:
# Reescalar imagen
Nx, Ny = 512,512
image=cv2.resize(image,(Nx,Ny))
# Escala de grises
image_gray=cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
cv2.imshow('ImagenGrayScale',image_gray)
# Conversion a punto flotante para realizar matematicas
image_gray_float=np.float64(image_gray)

In [5]:
# Obtener la fft

FFT = np.fft.fft2(image_gray_float)
FFT = np.fft.fftshift(FFT)

# Obtener la magnitud de la transformada de Fourier

FFTA = np.abs(FFT)

# Escalar en logaritmos

FFTLog = 20*np.log10(FFTA)

In [42]:
# Mostrar la imagen en su espectro de frecuencias

cv2.imshow('Espectro de Fourier', np.uint8(255*FFTLog/np.max(FFTLog)) )

In [7]:
# Vamos a diseñar el filtro para nuestra imagen

F1 = np.arange( -0.5*Nx+1, 0.5*Nx+1, 1)
F2 = np.arange( -0.5*Ny+1, 0.5*Ny+1, 1)
[X, Y] = np.meshgrid(F1,F2)
D = np.sqrt(X**2 + Y**2)
D = D/np.max(D)
print(D)

[[0.99609375 0.99414254 0.99219519 ... 0.99414254 0.99609375 0.99804879]
 [0.99414254 0.9921875  0.9902363  ... 0.9921875  0.99414254 0.99610141]
 [0.99219519 0.9902363  0.98828125 ... 0.9902363  0.99219519 0.99415789]
 ...
 [0.99414254 0.9921875  0.9902363  ... 0.9921875  0.99414254 0.99610141]
 [0.99609375 0.99414254 0.99219519 ... 0.99414254 0.99609375 0.99804879]
 [0.99804879 0.99610141 0.99415789 ... 0.99610141 0.99804879 1.        ]]


In [43]:
# Definimos un radio de corte

D0 = 0.05
D02 = 0.7

Huv = np.zeros((Nx,Ny))

#Filtro de bajas frecuencias

for i in range(Nx):
    for j in range(Ny):
        if(D[i,j] < D0):
            Huv[i,j] = 1.
        #if(D[i,j] > D02):
        #    Huv[i,j] = 1.
            
#print(Huv)

In [44]:
cv2.imshow('FiltrodeBajaF', np.uint8(255*Huv))

In [45]:
# Usemos el teorema de convolucion

Guv = Huv*FFT

In [46]:
# Calculamos la magnitud

GuvA = np.abs(Guv)

# Escalamos

GuvA = np.uint8( 255*GuvA/np.max(GuvA) )

In [47]:
# Visualizar el espectro con filtro
cv2.imshow('Espectro_Fourier_Filtro', np.uint8( 255*GuvA ))

In [48]:

# Ahora tomemos la transformada inversa para obtener la imagen fina

Gxy = np.fft.ifft2(Guv)
Gxy = np.abs(Gxy)
Gxy = np.uint8(Gxy)

In [49]:
cv2.imshow('ImagenConFiltro',Gxy)