In [1]:
# %matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

import mglearn
import sklearn
from sklearn.decomposition import PCA
from sklearn.datasets import load_breast_cancer

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2.,1.,4.]])
print(M)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]


In [3]:
b = np.array([1.,3.,7.])
print(b)

[1. 3. 7.]


# Método de eliminación Gaussiana

1. Diagonalizar la matriz con unos en la diagonal
2. Hacer la sustiución hacia atrás $ x_{i} = \frac{b_{i} - \sum_{j = i+1}^{n} a_{ij}x_{j}}{a_{ii}} $

In [11]:
def GetGaussianElimination(M_, b_):
    A = M_.copy()
    b = b_.copy()
    
    A = np.float_(A)
    b = np.float_(b)
    n=len(b)
    
    for i in range(n):
        # unos en la diagonal
        a = A[i,i]
        A[i,:] = A[i,:]/a # Dividir toda fila por el valor de la diagonal
        b[i] = b[i]/a
        
        print(A)
        for j in range(i+1, n):
            a = A[j,i] # Tomar el primer elemento de la segunda fila
            A[j,:] = A[j,:] - a*A[i,:] # multiplica el elemento por la fila anterior y suma con la fila actual
            b[j] = b[j] - a*b[i]
    
    x = b.copy()
    
    return x, A, b

In [12]:
Xsol, NewM, Newb = GetGaussianElimination(M,b)
print(Xsol)

[[ 1.         -0.33333333 -0.33333333]
 [-1.          3.          1.        ]
 [ 2.          1.          4.        ]]
[[ 1.         -0.33333333 -0.33333333]
 [ 0.          1.          0.25      ]
 [ 0.          1.66666667  4.66666667]]
[[ 1.         -0.33333333 -0.33333333]
 [ 0.          1.          0.25      ]
 [ 0.          0.          1.        ]]
[0.33333333 1.25       1.        ]
